# Generated by Django 3.2.9 on 2022-01-17 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_auto_20211219_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bdate',
            field=models.CharField(blank=True, max_length=10, verbose_name='дата рождения'),
        ),
    ]
